sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - stable
  - 6
os:
  - linux
before_script:
  - yarn install
  - yarn link || true
  - npm test
  - npm run lint
after_success:
  - npm install codecov -g
  - npm run postcover
